#
# makefile creado autom‡ticamente con JMake
#
program.jar: JTabbedPaneColores.class   /com/coti/guitools/JFrameAI.class  
	jar cmfv manifest program.jar /com/coti/guitools/JFrameAI.class  JTabbedPaneColores.class  
/com/coti/guitools/JFrameAI.class : /com/coti/guitools/JFrameAI.java 
	javac /com/coti/guitools/JFrameAI.java 




JTabbedPaneColores.class : JTabbedPaneColores.java 
	javac JTabbedPaneColores.java 


lean:
	rm -rf *.class
	rm -rf /com/coti/guitools/*.class
	rm -rf /com/coti/textfiletools/*.class
clean:
	rm -rf *.class
	rm -rf program.jar
